### PR TITLE
Upgrade to preact X

### PR DESCRIPTION
**Pull request by psabharwal123**
upgrade to work with preact X

### CODE REVIEW

**Comment by psabharwal123** [comment]
also pinging @ForsakenHarmony and @prateekbh incase you guys have write acces

**Comment by ForsakenHarmony** [comment]
nop

**Comment by prateekbh** [comment]
nope

**Comment by psabharwal123** [comment]
@developit i removed setTimeout from componentDidUpdate since that was causing flicker issues with animations

**Comment by Akiyamka** [comment]
@developit I understand that you are very busy, but maybe you have time to click one button here

**Review by Akiyamka — APPROVED** [review]
LGFM

**Review by developit — APPROVED** [review]
LTM. apologies for the wait.

**Comment by developit** [comment]
Released as [2.0.0](https://github.com/developit/preact-transition-group/releases/tag/2.0.0).

**Pull request merged**
